name: Buf Push

on:
  push:
    branches: [main]
    paths:
      - 'proto/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: bufbuild/buf-action@v1
        with:
          input: proto
          push: true
          token: ${{ secrets.BUF_TOKEN }}
